id = "abacatepay-theme"
name = "AbacatePay Theme"
version = "0.1.12"
schema_version = 1
authors = ["AbacatePay <contato@abacatepay.com>"]
description = "A green-first theme designed for AbacatePay."
repository = "https://github.com/AbacatePay/vscode-theme"
