id = "palanca-theme"
name = "Palanca Theme"
version = "0.0.1"
schema_version = 1
authors = ["ClemilsonAzevedo <clemilsondeazevedo@gmail.com>"]
description = "Um tema Dark inspirado no Vesper"
repository = "https://github.com/clemilsonazevedo/palanca-theme"
