[assembly]
path = "extensions/assembly"
version = "0.0.1"

[base16]
path = "extensions/base16"
version = "0.0.3"

[beancount]
path = "extensions/beancount"
version = "0.0.1"

[brainfuck]
path = "extensions/brainfuck"
version = "0.0.2"

[catppuccin]
path = "extensions/catppuccin"
version = "0.1.1"

[dockerfile]
path = "extensions/dockerfile"
version = "0.0.1"

[dracula]
path = "extensions/dracula"
version = "0.0.1"

[elisp]
path = "extensions/elisp"
version = "0.0.2"

[everforest]
path = "extensions/everforest"
version = "0.0.2"

[exquisite]
path = "extensions/exquisite"
version = "0.1.1"

[github-dark-default]
path = "extensions/github-dark-default"
version = "0.0.1"

[github-theme]
path = "extensions/github-theme"
version = "0.0.1"

[graphene]
path = "extensions/graphene"
version = "0.1.0"

[graphql]
path = "extensions/graphql"
version = "0.0.1"

[horizon]
path = "extensions/horizon"
version = "0.0.1"

[java]
path = "extensions/java"
version = "0.0.2"

[kiselevka]
path = "extensions/kiselevka"
version = "0.0.1"

[log]
path = "extensions/log"
version = "0.0.2"

[macos-classic]
path = "extensions/macos-classic"
version = "0.0.4"

[mau]
path = "extensions/mau"
version = "0.0.1"

[mellow]
path = "extensions/mellow"
version = "0.0.1"

[msun-dark]
path = "extensions/msun-dark"
version = "0.0.3"

[muted]
path = "extensions/muted"
version = "0.0.1"

[napalm]
path = "extensions/napalm"
version = "0.0.2"

[navi]
path = "extensions/navi"
version = "0.0.2"

[neosolarized]
path = "extensions/neosolarized"
version = "0.0.1"

[new-darcula]
path = "extensions/new-darcula"
version = "1.0.2"

[night-owlz]
path = "extensions/night-owlz"
version = "0.0.1"

[nightfox]
path = "extensions/nightfox"
version = "0.0.1"

[nu]
path = "extensions/nu"
version = "0.0.1"

[one-dark-pro]
path = "extensions/one-dark-pro"
version = "0.0.1"

[pkl]
path = "extensions/pkl"
version = "0.0.1"

[poimandres]
path = "extensions/poimandres"
version = "0.0.1"

[r]
path = "extensions/r"
version = "0.0.1"

[smithy]
path = "extensions/smithy"
version = "0.0.1"

[smooth]
path = "extensions/smooth"
version = "0.0.1"

[sql]
path = "extensions/sql"
version = "0.0.2"

[srcery]
path = "extensions/srcery"
version = "0.0.1"

[swift]
path = "extensions/swift"
version = "0.0.4"

[synthwave]
path = "extensions/synthwave"
version = "0.0.1"

[the-dark-side]
path = "extensions/the-dark-side"
version = "0.2.2"

[tokyo-night]
path = "extensions/tokyo-night"
version = "0.0.2"

[ultimate-dark-neo]
path = "extensions/ultimate-dark-neo"
version = "0.0.1"

[vscode-dark-plus]
path = "extensions/vscode-dark-plus"
version = "0.0.1"

[vscode-monokai-charcoal]
path = "extensions/vscode-monokai-charcoal"
version = "0.0.1"

[wgsl]
path = "extensions/wgsl"
version = "0.0.1"

[xcode-themes]
path = "extensions/xcode-themes"
version = "1.0.0"

[xy-zed]
path = "extensions/xy-zed"
version = "0.0.4"

[zedokai]
path = "extensions/zedokai"
version = "0.1.0"

[zedspace]
path = "extensions/zedspace"
version = "0.0.1"
