[alabaster]
submodule = "extensions/alabaster"
version = "0.0.2"

[assembly]
submodule = "extensions/assembly"
version = "0.0.1"

[astro]
submodule = "extensions/zed"
path = "extensions/astro"
version = "0.0.1"

[base16]
submodule = "extensions/base16"
version = "0.0.4"

[beancount]
submodule = "extensions/beancount"
version = "0.0.1"

[blanche]
submodule = "extensions/blanche"
version = "0.0.1"

[brainfuck]
submodule = "extensions/brainfuck"
version = "0.0.3"

[cadence]
submodule = "extensions/cadence"
version = "0.0.1"

[catppuccin]
submodule = "extensions/catppuccin"
version = "0.2.5"

[clojure]
submodule = "extensions/zed"
path = "extensions/clojure"
version = "0.0.1"

[colorizer]
submodule = "extensions/colorizer"
version = "0.0.3"

[cosmos]
submodule = "extensions/cosmos"
version = "0.0.1"

[csharp]
submodule = "extensions/zed"
path = "extensions/csharp"
version = "0.0.1"

[cue]
submodule = "extensions/cue"
version = "0.0.1"

[d]
submodule = "extensions/d"
version = "0.0.3"

[dockerfile]
submodule = "extensions/dockerfile"
version = "0.0.2"

[dracula]
submodule = "extensions/dracula"
version = "0.7.3"

[elisp]
submodule = "extensions/elisp"
version = "0.0.3"

[ember]
submodule = "extensions/ember"
version = "0.0.1"

[emmet]
submodule = "extensions/zed"
path = "extensions/emmet"
version = "0.0.1"

[erlang]
submodule = "extensions/zed"
path = "extensions/erlang"
version = "0.0.1"

[everforest]
submodule = "extensions/everforest"
version = "0.0.2"

[exquisite]
submodule = "extensions/exquisite"
version = "0.1.1"

[fish]
submodule = "extensions/fish"
version = "0.0.6"

[fleet-themes]
submodule = "extensions/fleet-themes"
version = "1.0.0"

[gdscript]
submodule = "extensions/gdscript"
version = "0.0.2"

[gentle-dark]
submodule = "extensions/gentle-dark"
version = "0.0.2"

[git-firefly]
submodule = "extensions/git-firefly"
version = "0.0.2"

[github-dark-default]
submodule = "extensions/github-dark-default"
version = "0.0.1"

[github-theme]
submodule = "extensions/github-theme"
version = "0.0.2"

[gleam]
submodule = "extensions/zed"
path = "extensions/gleam"
version = "0.0.2"

[graphene]
submodule = "extensions/graphene"
version = "0.1.0"

[graphql]
submodule = "extensions/graphql"
version = "0.0.2"

[haskell]
submodule = "extensions/zed"
path = "extensions/haskell"
version = "0.0.1"

[horizon]
submodule = "extensions/horizon"
version = "0.0.1"

[html]
submodule = "extensions/zed"
path = "extensions/html"
version = "0.0.1"

[indigo]
submodule = "extensions/indigo"
version = "0.0.2"

[java]
submodule = "extensions/java"
version = "0.0.3"

[kiselevka]
submodule = "extensions/kiselevka"
version = "0.0.1"

[kotlin]
submodule = "extensions/kotlin"
version = "0.0.1"

[ktrz-monokai]
submodule = "extensions/ktrz-monokai"
version = "0.0.2"

[latex]
submodule = "extensions/latex"
version = "0.0.2"

[log]
submodule = "extensions/log"
version = "0.0.3"

[macos-classic]
submodule = "extensions/macos-classic"
version = "0.0.6"

[make]
submodule = "extensions/make"
version = "1.0.0"

[markdown-oxide]
submodule = "extensions/markdown-oxide"
version = "0.0.4"

[material-dark]
submodule = "extensions/material-dark"
version = "0.0.1"

[matlab]
submodule = "extensions/matlab"
version = "0.0.1"

[mau]
submodule = "extensions/mau"
version = "0.0.1"

[mellow]
submodule = "extensions/mellow"
version = "0.0.1"

[modest-dark]
submodule = "extensions/modest-dark"
version = "0.1.1"

[msun-dark]
submodule = "extensions/msun-dark"
version = "0.0.4"

[muted]
submodule = "extensions/muted"
version = "0.0.1"

[nanowise]
submodule = "extensions/nanowise"
version = "0.1.0"

[napalm]
submodule = "extensions/napalm"
version = "0.0.2"

[navi]
submodule = "extensions/navi"
version = "0.1.0"

[neosolarized]
submodule = "extensions/neosolarized"
version = "0.0.1"

[new-darcula]
submodule = "extensions/new-darcula"
version = "1.0.5"

[night-owlz]
submodule = "extensions/night-owlz"
version = "0.0.2"

[nightfox]
submodule = "extensions/nightfox"
version = "0.0.1"

[nix]
submodule = "extensions/nix"
version = "0.0.4"

[nord]
submodule = "extensions/nord"
version = "0.0.2"

[norrsken]
submodule = "extensions/norrsken"
version = "0.0.2"

[nu]
submodule = "extensions/nu"
version = "0.0.1"

[oceanic-next]
submodule = "extensions/oceanic-next"
version = "0.1.0"

[one-dark-pro]
submodule = "extensions/one-dark-pro"
version = "0.0.3"

[one-hunter]
submodule = "extensions/one-hunter"
version = "0.0.2"

[pact]
submodule = "extensions/pact"
version = "0.0.1"

[paraiso]
submodule = "extensions/paraiso"
version = "1.0.1"

[penumbra]
submodule = "extensions/penumbra"
version = "0.0.1"

[pest]
submodule = "extensions/pest"
version = "0.1.0"

[php]
submodule = "extensions/zed"
path = "extensions/php"
version = "0.0.1"

[pkl]
submodule = "extensions/pkl"
version = "0.1.0"

[poimandres]
submodule = "extensions/poimandres"
version = "0.0.1"

[prisma]
submodule = "extensions/zed"
path = "extensions/prisma"
version = "0.0.1"

[purescript]
submodule = "extensions/zed"
path = "extensions/purescript"
version = "0.0.1"

[r]
submodule = "extensions/r"
version = "0.0.1"

[scala]
submodule = "extensions/scala"
version = "0.0.1"

[siri]
submodule = "extensions/siri"
version = "0.0.3"

[slint]
submodule = "extensions/slint"
version = "0.0.2"

[smithy]
submodule = "extensions/smithy"
version = "0.0.1"

[smooth]
submodule = "extensions/smooth"
version = "1.0.0"

[solarized-fp]
submodule = "extensions/solarized-fp"
version = "0.0.1"

[solidity]
submodule = "extensions/solidity"
version = "0.0.3"

[sql]
submodule = "extensions/sql"
version = "0.0.2"

[srcery]
submodule = "extensions/srcery"
version = "0.0.2"

[starlark]
submodule = "extensions/starlark"
version = "0.1.1"

[svelte]
submodule = "extensions/zed"
path = "extensions/svelte"
version = "0.0.1"

[swift]
submodule = "extensions/swift"
version = "0.1.0"

[synthwave]
submodule = "extensions/synthwave"
version = "0.0.1"

[templ]
submodule = "extensions/templ"
version = "0.0.1"

[the-dark-side]
submodule = "extensions/the-dark-side"
version = "0.2.4"

[tokyo-night]
submodule = "extensions/tokyo-night"
version = "0.0.2"

[toml]
submodule = "extensions/zed"
path = "extensions/toml"
version = "0.0.2"

[uiua]
submodule = "extensions/zed"
path = "extensions/uiua"
version = "0.0.1"

[ultimate-dark-neo]
submodule = "extensions/ultimate-dark-neo"
version = "0.0.3"

[vesper]
submodule = "extensions/vesper"
version = "0.0.1"

[visual-assist-dark]
submodule = "extensions/visual-assist-dark"
version = "0.0.2"

[vitesse]
submodule = "extensions/vitesse"
version = "0.0.1"

[vscode-dark-plus]
submodule = "extensions/vscode-dark-plus"
version = "0.0.1"

[vscode-monokai-charcoal]
submodule = "extensions/vscode-monokai-charcoal"
version = "0.0.2"

[wgsl]
submodule = "extensions/wgsl"
version = "0.0.1"

[xcode-themes]
submodule = "extensions/xcode-themes"
version = "1.1.2"

[xy-zed]
submodule = "extensions/xy-zed"
version = "0.0.11"

[zedokai]
submodule = "extensions/zedokai"
version = "1.1.0"

[zedspace]
submodule = "extensions/zedspace"
version = "0.0.1"

[zig]
submodule = "extensions/zed"
path = "extensions/zig"
version = "0.0.1"
