[beancount]
path = "extensions/beancount"
version = "0.0.1"

[neosolarized]
path = "extensions/neosolarized"
version = "0.0.1"

[vscode-dark-plus]
path = "extensions/vscode-dark-plus"
version = "0.0.1"
