id = "zk"
name = "zk"
description = "Zettelkasten note-taking assistant with language server support for Markdown"
version = "0.0.1"
schema_version = 1
authors = ["Zed Extensions <extensions@zed.dev>"]
repository = "https://github.com/zk-org/zk"

[language_servers.zk]
name = "zk"
language = "Markdown"
