id = "codely-theme-blur"
name = "Floral Theme"
schema_version = 1
version = "1.0.0"
description = "Soft-pink light theme"
authors = ["laynexx <argo150808@gmail.com>"]
repository = "https://github.com/laynexx-ns/floral-theme-zed"
