id = "matte-black-theme"
name = "Matte Black Pro Theme v0.1.1"
version = "0.1.1"
schema_version = 1
authors = ["Youpele <mjayjesus@gmail.com>"]
description = "Find your Zen in Zed.  a meticulously crafted, dark matte black theme that marries minimalist aesthetics with carefully tuned syntax colors. Created for discerning developers who seek a distraction-free, high-performance coding environment."
repository = "https://github.com/youpele52/matte-black-theme"
license = "MIT"
categories = ["themes"]
