id = "matte-black-theme"
name = "Matte Black Theme v0.1.0"
version = "0.1.0"
schema_version = 1
authors = ["Youpele <mjayjesus@gmail.com>"]
description = "Find your Zen in Zed. A dark, matte black theme designed for focused coding with carefully tuned syntax colors and high contrast. Embrace simplicity, enhance clarity."
repository = "https://github.com/youpele52/matte-black-theme"
license = "MIT"
categories = ["themes"]
