id = "denix"
name = "Denix Theme"
version = "0.0.3"
schema_version = 1
authors = ["Denis Salmanovich <denis.salmanovich@gmail.com>"]
description = "üêß DeniX theme for Zed editor"
repository = "https://github.com/denix666/zed-theme"
