name: CI

on:
  pull_request:
  push:
    branches:
      - "main"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          clean: false
          fetch-depth: 0
          # TODO: Checkout submodules individually to speed up CI.
          # We just need to figure out the Git authentication story.
          submodules: "recursive"

      - name: Checkout Zed repo
        uses: actions/checkout@v4
        with:
          repository: zed-industries/zed
          path: "./zed"
          clean: false
          submodules: "recursive"

      - uses: pnpm/action-setup@v3
        with:
          version: 8

      - uses: actions/setup-node@v3
        with:
          node-version: "20"
          cache: "pnpm"

      - name: Install Emscripten
        uses: mymindstorm/setup-emsdk@v14
        with:
          version: "3.1.37"
          actions-cache-folder: "emsdk-cache"

      - name: Build extension CLI
        shell: bash -euxo pipefail {0}
        run: |
          cd zed
          ./script/linux
          cargo build --release --package extension_cli
          cd -

      - name: Install dependencies
        run: pnpm install

      - name: Run tests
        run: pnpm test

      - name: Package extensions
        run: pnpm package-extensions
        env:
          SHOULD_PUBLISH: ${{ github.ref_name == 'main' }}
          S3_BUCKET: ${{ secrets.S3_BUCKET }}
          S3_ACCESS_KEY: ${{ secrets.S3_ACCESS_KEY }}
          S3_SECRET_KEY: ${{ secrets.S3_SECRET_KEY }}

      - name: Enforce sorted `extensions.toml`
        run: git diff --exit-code -- extensions.toml

      - name: Enforce sorted `.gitmodules`
        run: git diff --exit-code -- .gitmodules
